#!/bin/bash

set -eu

source $(dirname "$0")/activate
source $(dirname "$0")/os


function fixture {
    os_setup

    tobiko-fixture "$@"
}


if [ $(basename "$0") == fixture ]; then
    fixture "$@"
fi
