#!/bin/bash

set -eu

source $(dirname "$0")/activate
source $(dirname "$0")/os


function keystone_credentials {
    os_setup

    tobiko-keystone-credentials "$@"
}


if [ $(basename "$0") == keystone-credentials ]; then
    keystone_credentials "$@"
fi
