#!/usr/bin/env python

import json
import io
import sys
import yaml


def main(args=None):
    args = args or sys.argv[1:]

    if args:
        input_stream = io.open(args[0], 'rb')
        args = args[1:]
    else:
        input_stream = sys.stdin

    with input_stream:
        data = yaml.load(input_stream)

    json.dump(data, sys.stdout, indent=4)


if __name__ == '__main__':
    main()
