- project:
    templates:
      - ansible-role-jobs
      - build-openstack-docs-pti
      - build-release-notes-jobs-python3
      - check-requirements
      - devstack-tobiko
      - devstack-tobiko-functional
      - devstack-tobiko-heat
      - devstack-tobiko-minimal
      - devstack-tobiko-octavia
      - devstack-tobiko-neutron
      - devstack-tobiko-nova
      - devstack-tobiko-ovs
      - devstack-tobiko-sanity
      - devstack-tobiko-storage
      - docs-on-readthedocs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - openstack-python3-yoga-jobs-arm64
      - publish-to-pypi
      - tobiko-docker
      - tobiko-infrared
      - tobiko-tripleo
    vars:
        rtd_webhook_id: '84947'
    periodic:
      jobs:
        - requirements-check:
            voting: true
